image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose

testApi:
  stage: test
  script:
    - cd api/
    - docker-compose -f docker-compose.tests.yml build
    - docker-compose -f docker-compose.tests.yml run -e RAILS_ENV=test -e RACK_ENV=test api
      /bin/sh -c 'bundle install --with test development && bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/junit.xml'
  artifacts:
    reports:
      junit: api/tmp/junit.xml

testDashboard:
  stage: test
  script:
    - cd dashboard/
    - docker-compose -f docker-compose.tests.yml build
    - docker-compose -f docker-compose.tests.yml run -e RAILS_ENV=test -e RACK_ENV=test dashboard
      /bin/sh -c 'bundle install --with test development && bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/junit.xml'
  artifacts:
    reports:
      junit: dashboard/tmp/junit.xml


testWorker:
  stage: test
  script:
    - cd worker/
    - docker-compose -f docker-compose.tests.yml build
    - docker-compose -f docker-compose.tests.yml run -e RAILS_ENV=test -e RACK_ENV=test worker
      /bin/sh -c 'bundle install --with test development && bundle exec rspec --format progress --format RspecJunitFormatter --out tmp/junit.xml'
  artifacts:
    reports:
      junit: worker/tmp/junit.xml
