version: '3.6'
services:
  redis:
    image: "redis:3.2.8"
  mongo:
    image: "mongo:3.6"
  api:
    build:
      context: ../
      dockerfile: api/Dockerfile
    volumes:
      - .:/app
    links:
    - "mongo:mongo"
    - "redis:redis"